### PR TITLE
Run markdownlint on push and pull request

### PR DESCRIPTION
**Pull request by ajaust**
This PR adds an action to run markdownlint on push and pull_requests.

### CODE REVIEW

**Comment by ajaust** [comment]
I think we should discuss whether we agree with all the default rules (like "MD013 - Line length") or whether we want to adapt this to our liking. 

The overview over all rules can be found [here](https://github.com/markdownlint/markdownlint/blob/master/docs/RULES.md).

**Comment by uekerman** [comment]
I had a quick look at the rules. I would drop at least:

* 12
* 13
* 40

and adapt:

* 26 (question marks should be allowed)

We can also do more tuning on the way.

**Comment by ajaust** [comment]
**Changes**
I have added a configuration for markdownlint which
- Deactivates rules `MD012` and `MD040`. 
- Rule `MD013` is adapted to allow for lines with 99999 characters. This will allow long lines without line breaks, but will complain on overly wide tables or code blocks. I think too wide tables or code block could be an actual issue  thus I left the check activated. We can still adapt this, if it turns out to be a problem.
- Rule `MD026` has been adapted to allow for question marks as trailing punctuation in headlines. All other trailing punctuation in headlines is still forbidden.
- Rule `MD029` has been adapted such that an ordered list must have incrementing prefixes.
- Rule `MD033` is deactivated such that we can use raw HTML in the files.

Most changes were are following the example described in the [markdownlint GitHub Action](https://github.com/marketplace/actions/markdownlint-mdl-action).

**Observations/Questions**

- `MD002`: We get some complaints about missing top level headers in the markdown files, i.e. `# Top level header` is missing. We currently use the [Metadata extension](https://squidfunk.github.io/mkdocs-material/reference/meta-tags/) of the mkdocs theme. It adds appropriate metadata to the pages, but also sets the top-level header. We could do the following to avoid failing check
    1. Disable rule `MD002`.
    2. Add a dummy header/correct header also as markdown text to each markdown file.
    3. Stop using the metadata extension which forces us to use the correct header. This makes us loose metadata in the generated page.
    4. Do not set the title via the metadata extension which forces us to use the correct header. This makes us loose *some* metadata in the generated page.
- There are some further complaints by markdownlint, but these complaints look fine to me. This should be fixed once this PR is merged.

**References**
- [List of markdownlint rules](https://github.com/markdownlint/markdownlint/blob/master/docs/RULES.md#md026---trailing-punctuation-in-header)

**Comment by ajaust** [comment]
One thing I just realized now: Why do we want to allow several blank lines, i.e. `MD012`? I do not understand the rationale of deactivating this rule at the moment.

**Comment by uekerman** [comment]
Let's disable `MD002` then. The CI should help us, not produce more work :grin: 

> One thing I just realized now: Why do we want to allow several blank lines, i.e. MD012? I do not understand the rationale of deactivating this rule at the moment.

When looking at the md source code, having multiple blank lines sometimes helps to organize things better. Would you agree?

**Comment by ajaust** [comment]
> When looking at the md source code, having multiple blank lines sometimes helps to organize things better. Would you agree?

I am not completely convinced. If you want to organize things better, maybe you need a different section/headline or some other structure. Multiple blank lines will not be rendered such that you improved organization is lost when going from raw Markdown to rendered Markdown. However, I kept `MD012` deactivated. We can see if we want to change this later on.

**Changes**
- I deactivated `MD002` and `MD041` as both were concerned with the top-level header and produced errors.
- I added a very short section on how to run markdownlint locally in the README.

**Comment by ajaust** [comment]
Hm... seems like I messed something up while rebasing. I will see if I can fix it and if not open a new pull request.

**Comment by ajaust** [comment]
> Hm... seems like I messed something up while rebasing. I will see if I can fix it and if not open a new pull request.

This seems to be fine fixed.

**Pull request merged**
